version: '3.7'
services:
  swagger-ui:
    image: eu.gcr.io/sbat-gcr-develop/securebanking/ui/swagger:latest
    ports:
      - "4205:443"
    environment:
      DOMAIN: dev-ob.forgerock.financial
      TEMPLATE: forgerock
      # The following env vars are all based on DOMAIN but can be set with any value (interesting locally with different ports)
      # SWAGGER_JSON_URL: "https://rs.aspsp.DOMAIN/api-docs"
    volumes:
      - ./ssl/k-all.dev-ob.forgerock.financial.key:/etc/nginx/certs/dev-ob.forgerock.financial.key
      - ./ssl/all.dev-ob.forgerock.financial.crt:/etc/nginx/certs/dev-ob.forgerock.financial.crt
      - ./ssl/dev-ob.forgerock.financial.conf:/etc/nginx/conf.d/default.conf

