apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- with .Values.ingress.additionalAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ .Chart.Name }}
    appVersion: {{ .Chart.AppVersion }}
    helmVersion: {{ .Chart.Version }}
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.rcsUI.subdomain }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-{{ .Values.rcsUI.subdomain }}
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: {{ .Values.swaggerUI.subdomain }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-{{ .Values.swaggerUI.subdomain }}
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "{{ .Values.ingress.tls.subdomain }}.{{ .Values.ingress.domain }}"
    secretName: {{ .Values.ingress.tls.secretName }}
