deployment:
  apiVersion: apps/v1
  containerPort: 8080
  image:
    # repo: 
    # tag:
    imagePullPolicy: Always
  replicas: 1
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 0.5
      memory: 512Mi
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 25%
  strategyType: RollingUpdate
  templateName: forgerock

service:
  apiVersion: v1
  port: 8080
  protocol: TCP
  targetPort: 80
  type: ClusterIP
