domain: dev.forgerock.financial

rcs:
  subdomain: rcs-ui
  deployment:
    port: 80
    replicas: 1

    templateName: forgerock

    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%

    imagePullPolicy: Always

    imageOverride:
      enabled: true
      repo: eu.gcr.io/sbat-gcr-develop/securebanking/ui/rcs
      tag: latest

    resources: {}

swagger:
  subdomain: swagger
  deployment:
    port: 80
    replicas: 1

    templateName: forgerock

    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%

    imagePullPolicy: Always

    imageOverride:
      enabled: true
      repo: eu.gcr.io/sbat-gcr-develop/securebanking/ui/swagger
      tag: latest

    resources: {}

ingress:
  apiVersion: extensions/v1beta1
  class: nginx
  additionalAnnotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1m
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 100k
  domain: localhost
  tls:
    subdomain: "*"
    secretName: sslcert

apiVersion:
  service: v1
  deployment: apps/v1
