name: merge-master
run-name: Merge master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
env:
  SERVICE_NAME: rcs
  GIT_SHA_SHORT: $(echo ${{ github.sha }} | cut -c1-7)

jobs:
  buildRcs:
    runs-on: ubuntu-latest
    name: Build rcs image
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

        # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker

      - name: test
        run: |
          make docker tag=${{ env.GIT_SHA_SHORT }}
          docker tag eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/ui/${{ env.SERVICE_NAME }}:${{ env.GIT_SHA_SHORT }} eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/ui/${{ env.SERVICE_NAME }}:latest
          docker push --all-tags eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/ui/rcs

  deploy:
    runs-on: ubuntu-latest
    name: Synchronise dev cluster.
    needs: [buildRcs]
    steps:
      - uses: actions/checkout@v3

      - name: 'Deploy Service'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v SERVICE_NAME=ui-sapig'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/service-build'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        id: run-pipeline
