name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  HELM_DIRECTORY: _infra/helm/
  SERVICE_NAME: securebanking-ui

jobs:
  pr:
    runs-on: ubuntu-latest
    name: Create pr docker tag
    outputs:
      prTag: ${{ steps.tag.outputs.pr_number }}
    steps:
      - uses: actions/checkout@v2

      - name: pr docker tag
        id: tag
        run: |
          PR=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "$PR"
          echo ::set-output name=pr_number::pr-"$PR"

  auth:
    runs-on: ubuntu-latest
    name: Test and package auth ui
    needs: [pr]
    steps:
      - uses: actions/checkout@v2

      - name: Configure Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: lint
        run: |
          cd securebanking-auth-ui
          npm ci
          npm run lint

      - name: test
        run: |
          cd securebanking-auth-ui
          npm run test

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}

      - run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          make docker tag=${{ needs.pr.outputs.prTag }} service=auth

  rcs:
    runs-on: ubuntu-latest
    name: test and package rcs ui
    needs: [pr]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: lint
        run: |
          cd securebanking-rcs-ui
          npm ci
          npm run lint

      - name: test
        run: |
          cd securebanking-rcs-ui
          npm run test

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}

      - run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          make docker tag=${{ needs.pr.outputs.prTag }} service=rcs

  swagger:
    runs-on: ubuntu-latest
    name: package swagger ui
    needs: [pr]
    steps:
      - uses: actions/checkout@v2

      - name: Configure Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}

      - run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          make docker tag=${{ needs.pr.outputs.prTag }} service=swagger

  helm:
    runs-on: ubuntu-latest
    name: Check PR integrity
    needs: [swagger, auth, rcs]
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}

      - name: template helm
        run: |
          helm template $HELM_DIRECTORY/$SERVICE_NAME

      - name: package helm
        run: |
          make helm version=latest

      - name: Publish PR Chart
        run: |
          gsutil cp $SERVICE_NAME-*.tgz gs://${{ secrets.HELM_DEV_BUCKET }}/$SERVICE_NAME/
