name: PR - Build and Deploy
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '_infra/helm/**'

jobs:
  run_pr-template:
    name: PR - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@1389-standard-steps-for-workflows
    secrets: inherit
    with:
      componentName: secure-api-gateway-ob-uk-ui
      dockerTag: pr-${{ github.event.number }}
