name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  HELM_DIRECTORY: _infra/helm/
  SERVICE_NAME: securebanking-ui

jobs:
  pr:
    runs-on: ubuntu-latest
    name: Check auth ui integrity
    outputs:
      prTag: ${{ needs.pr.outputs.prTag }}
    steps:
      - name: pr docker tag
        id: tag
        run: |
          PR=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "$PR"
          echo ::set-output name=pr_number::pr-"$PR"

  auth:
    runs-on: ubuntu-latest
    name: Check auth ui integrity
    needs: [pr]
    steps:
      - name: lint
        run: |
          cd securebaking-auth-ui
          npm run lint

      - name: test
        run: |
          cd securebaking-auth-ui
          npm run test
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}

      - run: |
          gcloud auth configure-docker
      
      - name: Build Docker Image
        run: |
          make docker tag=latest service=auth
          docker tag eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/auth:latest eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/auth:${{ needs.pr.outputs.prTag }}
          docker push eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/auth:${{ needs.pr.outputs.prTag }}
          

  rcs:
    runs-on: ubuntu-latest
    name: Check auth ui integrity
    needs: [pr]
    steps:
      - name: lint
        run: |
          cd securebaking-rcs-ui
          npm run lint

      - name: test
        run: |
          cd securebaking-rcs-ui
          npm run test
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
      
      - run: |
          gcloud auth configure-docker
      
      - name: Build Docker Image
        run: |
          make docker tag=latest service=rcs
          docker tag eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/rcs:latest eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/rcs:${{ needs.pr.outputs.prTag }}
          docker push eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/rcs:${{ needs.pr.outputs.prTag }}

  swagger:
    runs-on: ubuntu-latest
    name: Check auth ui integrity
    needs: [pr]
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
      
      - run: |
          gcloud auth configure-docker
      
      - name: Build Docker Image
        run: |
          make docker tag=latest service=swagger
          docker tag eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/swagger:latest eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/swagger:${{ needs.pr.outputs.prTag }}
          docker push eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking-ui/swagger:${{ needs.pr.outputs.prTag }}
    
  helm:
    runs-on: ubuntu-latest
    name: Check PR integrity
    needs: [swagger, auth, rcs]
    steps:
      - uses: actions/checkout@v2
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
      
      - name: template helm
        run: |
          helm template $HELM_DIRECTORY/$SERVICE_NAME
    
      - name: package helm
        run: |
          make helm version=latest
      
      - name: Publish PR Chart
        run: |
          gsutil cp $SERVICE_NAME-*.tgz gs://${{ secrets.HELM_DEV_BUCKET }}/$SERVICE_NAME/
